apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: cinema-booking
  labels:
    app: gateway
data:
  PORT: "3333"
  GIN_MODE: "release"
  ENVIRONMENT: "production"
  DOMAIN: "localhost"
  USERS_SERVICE_ADDRESS: "users-svc:50051"
  BOOKINGS_SERVICE_ADDRESS: "bookings-svc:50052"
  SEATS_SERVICE_ADDRESS: "seats-svc:50053"
  REDIS_DB: "0"
