apiVersion: v1
kind: ConfigMap
metadata:
  name: seats-config
  namespace: cinema-booking
  labels:
    app: seats
data:
  PORT: "50053"
  ENVIRONMENT: "production"
  GIN_MODE: "release"
  DOMAIN: "localhost"
  DATABASE_HOST: "your-neon-seats-host.neon.tech"
  DATABASE_PORT: "5432"
  DATABASE_USERNAME: "neondb_owner"
  DATABASE_NAME: "seat_service"
