// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/booking.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_SEAT_UNSPECIFIED Status = 0
	Status_STATUS_AVAILABLE        Status = 1
	Status_STATUS_HOLD             Status = 2
	Status_STATUS_BOOKED           Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_SEAT_UNSPECIFIED",
		1: "STATUS_AVAILABLE",
		2: "STATUS_HOLD",
		3: "STATUS_BOOKED",
	}
	Status_value = map[string]int32{
		"STATUS_SEAT_UNSPECIFIED": 0,
		"STATUS_AVAILABLE":        1,
		"STATUS_HOLD":             2,
		"STATUS_BOOKED":           3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_booking_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_booking_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{0}
}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SeatId        int64                  `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,3,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	MovieId       int64                  `protobuf:"varint,6,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_api_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{0}
}

func (x *Booking) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Booking) GetSeatId() int64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *Booking) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *Booking) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Booking) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Booking) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId       int64                  `protobuf:"varint,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	SeatIds       []int64                `protobuf:"varint,3,rep,packed,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRequest) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *CreateRequest) GetSeatIds() []int64 {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_api_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HoldBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId       int64                  `protobuf:"varint,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	SeatId        int64                  `protobuf:"varint,3,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldBookingRequest) Reset() {
	*x = HoldBookingRequest{}
	mi := &file_api_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldBookingRequest) ProtoMessage() {}

func (x *HoldBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldBookingRequest.ProtoReflect.Descriptor instead.
func (*HoldBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{3}
}

func (x *HoldBookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HoldBookingRequest) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *HoldBookingRequest) GetSeatId() int64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

type HoldBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldBookingResponse) Reset() {
	*x = HoldBookingResponse{}
	mi := &file_api_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldBookingResponse) ProtoMessage() {}

func (x *HoldBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldBookingResponse.ProtoReflect.Descriptor instead.
func (*HoldBookingResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{4}
}

func (x *HoldBookingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FindAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId       int64                  `protobuf:"varint,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllRequest) Reset() {
	*x = FindAllRequest{}
	mi := &file_api_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRequest) ProtoMessage() {}

func (x *FindAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRequest.ProtoReflect.Descriptor instead.
func (*FindAllRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindAllRequest) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type FindAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllResponse) Reset() {
	*x = FindAllResponse{}
	mi := &file_api_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllResponse) ProtoMessage() {}

func (x *FindAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllResponse.ProtoReflect.Descriptor instead.
func (*FindAllResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type IsSeatAvailableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        int64                  `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	MovieId       int64                  `protobuf:"varint,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsSeatAvailableRequest) Reset() {
	*x = IsSeatAvailableRequest{}
	mi := &file_api_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsSeatAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsSeatAvailableRequest) ProtoMessage() {}

func (x *IsSeatAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsSeatAvailableRequest.ProtoReflect.Descriptor instead.
func (*IsSeatAvailableRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{7}
}

func (x *IsSeatAvailableRequest) GetSeatId() int64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *IsSeatAvailableRequest) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type IsSeatAvailableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsSeatAvailableResponse) Reset() {
	*x = IsSeatAvailableResponse{}
	mi := &file_api_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsSeatAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsSeatAvailableResponse) ProtoMessage() {}

func (x *IsSeatAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsSeatAvailableResponse.ProtoReflect.Descriptor instead.
func (*IsSeatAvailableResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{8}
}

func (x *IsSeatAvailableResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *IsSeatAvailableResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     int64                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	NewSeatId     int64                  `protobuf:"varint,2,opt,name=new_seat_id,json=newSeatId,proto3" json:"new_seat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRequest) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *UpdateRequest) GetNewSeatId() int64 {
	if x != nil {
		return x.NewSeatId
	}
	return 0
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_api_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookingId     int64                  `protobuf:"varint,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_api_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{11}
}

func (x *CancelRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelRequest) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     int64                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_api_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{12}
}

func (x *CancelResponse) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_booking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{13}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_booking_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{14}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_api_booking_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{15}
}

func (x *CreateUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_api_booking_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{16}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_api_booking_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{17}
}

func (x *LoginUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_api_booking_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdResponse) Reset() {
	*x = GetUserByIdResponse{}
	mi := &file_api_booking_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdResponse) ProtoMessage() {}

func (x *GetUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserByIdResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Row           string                 `protobuf:"bytes,3,opt,name=row,proto3" json:"row,omitempty"`
	Column        string                 `protobuf:"bytes,4,opt,name=column,proto3" json:"column,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_api_booking_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{20}
}

func (x *Seat) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Seat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Seat) GetRow() string {
	if x != nil {
		return x.Row
	}
	return ""
}

func (x *Seat) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *Seat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SetSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSeatsRequest) Reset() {
	*x = SetSeatsRequest{}
	mi := &file_api_booking_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSeatsRequest) ProtoMessage() {}

func (x *SetSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSeatsRequest.ProtoReflect.Descriptor instead.
func (*SetSeatsRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{21}
}

type SetSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSeatsResponse) Reset() {
	*x = SetSeatsResponse{}
	mi := &file_api_booking_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSeatsResponse) ProtoMessage() {}

func (x *SetSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSeatsResponse.ProtoReflect.Descriptor instead.
func (*SetSeatsResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{22}
}

func (x *SetSeatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       int64                  `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatsRequest) Reset() {
	*x = GetSeatsRequest{}
	mi := &file_api_booking_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatsRequest) ProtoMessage() {}

func (x *GetSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatsRequest.ProtoReflect.Descriptor instead.
func (*GetSeatsRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{23}
}

func (x *GetSeatsRequest) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type GetSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seats         []*Seat                `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatsResponse) Reset() {
	*x = GetSeatsResponse{}
	mi := &file_api_booking_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatsResponse) ProtoMessage() {}

func (x *GetSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatsResponse.ProtoReflect.Descriptor instead.
func (*GetSeatsResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{24}
}

func (x *GetSeatsResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type GetOneSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        int64                  `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneSeatRequest) Reset() {
	*x = GetOneSeatRequest{}
	mi := &file_api_booking_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneSeatRequest) ProtoMessage() {}

func (x *GetOneSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneSeatRequest.ProtoReflect.Descriptor instead.
func (*GetOneSeatRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{25}
}

func (x *GetOneSeatRequest) GetSeatId() int64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

type GetOneSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          *Seat                  `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneSeatResponse) Reset() {
	*x = GetOneSeatResponse{}
	mi := &file_api_booking_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneSeatResponse) ProtoMessage() {}

func (x *GetOneSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneSeatResponse.ProtoReflect.Descriptor instead.
func (*GetOneSeatResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{26}
}

func (x *GetOneSeatResponse) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

type DeleteSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        int64                  `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSeatRequest) Reset() {
	*x = DeleteSeatRequest{}
	mi := &file_api_booking_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSeatRequest) ProtoMessage() {}

func (x *DeleteSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSeatRequest.ProtoReflect.Descriptor instead.
func (*DeleteSeatRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteSeatRequest) GetSeatId() int64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

type DeleteSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSeatResponse) Reset() {
	*x = DeleteSeatResponse{}
	mi := &file_api_booking_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSeatResponse) ProtoMessage() {}

func (x *DeleteSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSeatResponse.ProtoReflect.Descriptor instead.
func (*DeleteSeatResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteSeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_booking_proto protoreflect.FileDescriptor

const file_api_booking_proto_rawDesc = "" +
	"\n" +
	"\x11api/booking.proto\x12\x06api.v1\"\xbc\x01\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aseat_id\x18\x02 \x01(\x03R\x06seatId\x12\x1f\n" +
	"\vseat_number\x18\x03 \x01(\tR\n" +
	"seatNumber\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x05 \x01(\tR\buserName\x12\x19\n" +
	"\bmovie_id\x18\x06 \x01(\x03R\amovieId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"^\n" +
	"\rCreateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\x03R\amovieId\x12\x19\n" +
	"\bseat_ids\x18\x03 \x03(\x03R\aseatIds\"(\n" +
	"\x0eCreateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"a\n" +
	"\x12HoldBookingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\x03R\amovieId\x12\x17\n" +
	"\aseat_id\x18\x03 \x01(\x03R\x06seatId\"-\n" +
	"\x13HoldBookingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"D\n" +
	"\x0eFindAllRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\x03R\amovieId\">\n" +
	"\x0fFindAllResponse\x12+\n" +
	"\bbookings\x18\x01 \x03(\v2\x0f.api.v1.BookingR\bbookings\"L\n" +
	"\x16IsSeatAvailableRequest\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\x03R\x06seatId\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\x03R\amovieId\"Q\n" +
	"\x17IsSeatAvailableResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\rUpdateRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x03R\tbookingId\x12\x1e\n" +
	"\vnew_seat_id\x18\x02 \x01(\x03R\tnewSeatId\"(\n" +
	"\x0eUpdateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"G\n" +
	"\rCancelRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\x03R\tbookingId\"/\n" +
	"\x0eCancelResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x03R\tbookingId\"\\\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"Y\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"E\n" +
	"\x12CreateUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"D\n" +
	"\x11LoginUserResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"-\n" +
	"\x12GetUserByIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"7\n" +
	"\x13GetUserByIdResponse\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.api.v1.UserR\x04user\"l\n" +
	"\x04Seat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03row\x18\x03 \x01(\tR\x03row\x12\x16\n" +
	"\x06column\x18\x04 \x01(\tR\x06column\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\x11\n" +
	"\x0fSetSeatsRequest\",\n" +
	"\x10SetSeatsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\",\n" +
	"\x0fGetSeatsRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\x03R\amovieId\"6\n" +
	"\x10GetSeatsResponse\x12\"\n" +
	"\x05seats\x18\x01 \x03(\v2\f.api.v1.SeatR\x05seats\",\n" +
	"\x11GetOneSeatRequest\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\x03R\x06seatId\"6\n" +
	"\x12GetOneSeatResponse\x12 \n" +
	"\x04seat\x18\x01 \x01(\v2\f.api.v1.SeatR\x04seat\",\n" +
	"\x11DeleteSeatRequest\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\x03R\x06seatId\".\n" +
	"\x12DeleteSeatResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*_\n" +
	"\x06Status\x12\x1b\n" +
	"\x17STATUS_SEAT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STATUS_AVAILABLE\x10\x01\x12\x0f\n" +
	"\vSTATUS_HOLD\x10\x02\x12\x11\n" +
	"\rSTATUS_BOOKED\x10\x032\x9f\x03\n" +
	"\x0eBookingService\x129\n" +
	"\x06Create\x12\x15.api.v1.CreateRequest\x1a\x16.api.v1.CreateResponse\"\x00\x12H\n" +
	"\vHoldBooking\x12\x1a.api.v1.HoldBookingRequest\x1a\x1b.api.v1.HoldBookingResponse\"\x00\x12<\n" +
	"\aFindAll\x12\x16.api.v1.FindAllRequest\x1a\x17.api.v1.FindAllResponse\"\x00\x12T\n" +
	"\x0fIsSeatAvailable\x12\x1e.api.v1.IsSeatAvailableRequest\x1a\x1f.api.v1.IsSeatAvailableResponse\"\x00\x129\n" +
	"\x06Update\x12\x15.api.v1.UpdateRequest\x1a\x16.api.v1.UpdateResponse\"\x00\x129\n" +
	"\x06Cancel\x12\x15.api.v1.CancelRequest\x1a\x16.api.v1.CancelResponse\"\x002\xe2\x01\n" +
	"\vUserService\x12E\n" +
	"\n" +
	"CreateUser\x12\x19.api.v1.CreateUserRequest\x1a\x1a.api.v1.CreateUserResponse\"\x00\x12B\n" +
	"\tLoginUser\x12\x18.api.v1.LoginUserRequest\x1a\x19.api.v1.LoginUserResponse\"\x00\x12H\n" +
	"\vGetUserById\x12\x1a.api.v1.GetUserByIdRequest\x1a\x1b.api.v1.GetUserByIdResponse\"\x002\x9e\x02\n" +
	"\fSeatsService\x12?\n" +
	"\bSetSeats\x12\x17.api.v1.SetSeatsRequest\x1a\x18.api.v1.SetSeatsResponse\"\x00\x12?\n" +
	"\bGetSeats\x12\x17.api.v1.GetSeatsRequest\x1a\x18.api.v1.GetSeatsResponse\"\x00\x12E\n" +
	"\n" +
	"GetOneSeat\x12\x19.api.v1.GetOneSeatRequest\x1a\x1a.api.v1.GetOneSeatResponse\"\x00\x12E\n" +
	"\n" +
	"DeleteSeat\x12\x19.api.v1.DeleteSeatRequest\x1a\x1a.api.v1.DeleteSeatResponse\"\x00B&Z$github.com/ThuraMinThein/commons/apib\x06proto3"

var (
	file_api_booking_proto_rawDescOnce sync.Once
	file_api_booking_proto_rawDescData []byte
)

func file_api_booking_proto_rawDescGZIP() []byte {
	file_api_booking_proto_rawDescOnce.Do(func() {
		file_api_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_booking_proto_rawDesc), len(file_api_booking_proto_rawDesc)))
	})
	return file_api_booking_proto_rawDescData
}

var file_api_booking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_api_booking_proto_goTypes = []any{
	(Status)(0),                     // 0: api.v1.Status
	(*Booking)(nil),                 // 1: api.v1.Booking
	(*CreateRequest)(nil),           // 2: api.v1.CreateRequest
	(*CreateResponse)(nil),          // 3: api.v1.CreateResponse
	(*HoldBookingRequest)(nil),      // 4: api.v1.HoldBookingRequest
	(*HoldBookingResponse)(nil),     // 5: api.v1.HoldBookingResponse
	(*FindAllRequest)(nil),          // 6: api.v1.FindAllRequest
	(*FindAllResponse)(nil),         // 7: api.v1.FindAllResponse
	(*IsSeatAvailableRequest)(nil),  // 8: api.v1.IsSeatAvailableRequest
	(*IsSeatAvailableResponse)(nil), // 9: api.v1.IsSeatAvailableResponse
	(*UpdateRequest)(nil),           // 10: api.v1.UpdateRequest
	(*UpdateResponse)(nil),          // 11: api.v1.UpdateResponse
	(*CancelRequest)(nil),           // 12: api.v1.CancelRequest
	(*CancelResponse)(nil),          // 13: api.v1.CancelResponse
	(*User)(nil),                    // 14: api.v1.User
	(*CreateUserRequest)(nil),       // 15: api.v1.CreateUserRequest
	(*CreateUserResponse)(nil),      // 16: api.v1.CreateUserResponse
	(*LoginUserRequest)(nil),        // 17: api.v1.LoginUserRequest
	(*LoginUserResponse)(nil),       // 18: api.v1.LoginUserResponse
	(*GetUserByIdRequest)(nil),      // 19: api.v1.GetUserByIdRequest
	(*GetUserByIdResponse)(nil),     // 20: api.v1.GetUserByIdResponse
	(*Seat)(nil),                    // 21: api.v1.Seat
	(*SetSeatsRequest)(nil),         // 22: api.v1.SetSeatsRequest
	(*SetSeatsResponse)(nil),        // 23: api.v1.SetSeatsResponse
	(*GetSeatsRequest)(nil),         // 24: api.v1.GetSeatsRequest
	(*GetSeatsResponse)(nil),        // 25: api.v1.GetSeatsResponse
	(*GetOneSeatRequest)(nil),       // 26: api.v1.GetOneSeatRequest
	(*GetOneSeatResponse)(nil),      // 27: api.v1.GetOneSeatResponse
	(*DeleteSeatRequest)(nil),       // 28: api.v1.DeleteSeatRequest
	(*DeleteSeatResponse)(nil),      // 29: api.v1.DeleteSeatResponse
}
var file_api_booking_proto_depIdxs = []int32{
	1,  // 0: api.v1.FindAllResponse.bookings:type_name -> api.v1.Booking
	14, // 1: api.v1.GetUserByIdResponse.user:type_name -> api.v1.User
	21, // 2: api.v1.GetSeatsResponse.seats:type_name -> api.v1.Seat
	21, // 3: api.v1.GetOneSeatResponse.seat:type_name -> api.v1.Seat
	2,  // 4: api.v1.BookingService.Create:input_type -> api.v1.CreateRequest
	4,  // 5: api.v1.BookingService.HoldBooking:input_type -> api.v1.HoldBookingRequest
	6,  // 6: api.v1.BookingService.FindAll:input_type -> api.v1.FindAllRequest
	8,  // 7: api.v1.BookingService.IsSeatAvailable:input_type -> api.v1.IsSeatAvailableRequest
	10, // 8: api.v1.BookingService.Update:input_type -> api.v1.UpdateRequest
	12, // 9: api.v1.BookingService.Cancel:input_type -> api.v1.CancelRequest
	15, // 10: api.v1.UserService.CreateUser:input_type -> api.v1.CreateUserRequest
	17, // 11: api.v1.UserService.LoginUser:input_type -> api.v1.LoginUserRequest
	19, // 12: api.v1.UserService.GetUserById:input_type -> api.v1.GetUserByIdRequest
	22, // 13: api.v1.SeatsService.SetSeats:input_type -> api.v1.SetSeatsRequest
	24, // 14: api.v1.SeatsService.GetSeats:input_type -> api.v1.GetSeatsRequest
	26, // 15: api.v1.SeatsService.GetOneSeat:input_type -> api.v1.GetOneSeatRequest
	28, // 16: api.v1.SeatsService.DeleteSeat:input_type -> api.v1.DeleteSeatRequest
	3,  // 17: api.v1.BookingService.Create:output_type -> api.v1.CreateResponse
	5,  // 18: api.v1.BookingService.HoldBooking:output_type -> api.v1.HoldBookingResponse
	7,  // 19: api.v1.BookingService.FindAll:output_type -> api.v1.FindAllResponse
	9,  // 20: api.v1.BookingService.IsSeatAvailable:output_type -> api.v1.IsSeatAvailableResponse
	11, // 21: api.v1.BookingService.Update:output_type -> api.v1.UpdateResponse
	13, // 22: api.v1.BookingService.Cancel:output_type -> api.v1.CancelResponse
	16, // 23: api.v1.UserService.CreateUser:output_type -> api.v1.CreateUserResponse
	18, // 24: api.v1.UserService.LoginUser:output_type -> api.v1.LoginUserResponse
	20, // 25: api.v1.UserService.GetUserById:output_type -> api.v1.GetUserByIdResponse
	23, // 26: api.v1.SeatsService.SetSeats:output_type -> api.v1.SetSeatsResponse
	25, // 27: api.v1.SeatsService.GetSeats:output_type -> api.v1.GetSeatsResponse
	27, // 28: api.v1.SeatsService.GetOneSeat:output_type -> api.v1.GetOneSeatResponse
	29, // 29: api.v1.SeatsService.DeleteSeat:output_type -> api.v1.DeleteSeatResponse
	17, // [17:30] is the sub-list for method output_type
	4,  // [4:17] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_booking_proto_init() }
func file_api_booking_proto_init() {
	if File_api_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_booking_proto_rawDesc), len(file_api_booking_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_booking_proto_goTypes,
		DependencyIndexes: file_api_booking_proto_depIdxs,
		EnumInfos:         file_api_booking_proto_enumTypes,
		MessageInfos:      file_api_booking_proto_msgTypes,
	}.Build()
	File_api_booking_proto = out.File
	file_api_booking_proto_goTypes = nil
	file_api_booking_proto_depIdxs = nil
}
